REAL NUM,LAR1,LAR2
PRINT*,'HOW MANY NUMBERS DO U WANT TO READ'
READ*,N
LAR1=0.0
LAR2=0.0
I=1
PRINT*,'ENTER THE VALUES'
100 READ*,NUM
IF(NUM.LT.LAR1) GO TO 100
LAR2=LAR1
LAR1=NUM
I=I+1
IF(I.LE.N)GO TO 100
PRINT*,'LARGEST NUMBER IS',LAR1,'2ND LARGEST NUMBER IS',LAR2
STOP
END

