PRINT*,'HOW MANY YEARS DO YOU WANT TO DEPOSIT'
READ*,N
PRINT*,'ENTER AMOUNT AND RATE IN PERCENTAGE'
READ*,AMOUNT,RATE
RATE=(RATE/100.0)
I=1
100 AMOUNT=AMOUNT+(AMOUNT*RATE)
PRINT*,'YEAR:',I,'AMOUNT',AMOUNT
I=I+1
IF(I.LE.N) GO TO 100
STOP
END

