PRINT*,'ENTER MANY MANY FIBONACCI SEQUENCE YOU WANT'
READ*,N
PRINT*,'ENTER 1ST AND 2ND NUMBER OF FIBONACCCI SERIES(J<=K)'
READ*,J,K
L=3
!!BECAUSE 1ST AND 2ND ARE EVALUTED BEFORE
PRINT*,J
PRINT*,K
IF(N.LT.3) GO TO 20
100 M=J+K
PRINT*,M
J=K
K=M
L=L+1
IF(L.LT.N) GO TO 100
20 STOP
END
