PRINT*,'ENTER THE POPULATION OF A AND B RESPECTIVELY'
READ*,POPA,POPB
PRINT*,'ENTER THE GROWTH RATE IOF A AND B RESPECTIVELY'
READ*,RATEA,RATEB
RATEA=RATEA/100.0
RATEB=RATEB/100.0
N=0
100 POPA=POPA+(POPA*RATEA)
A=1000.0*NINT(POPA/1000.0)
POPB=POPB+(POPB*0.04)
B=1000.0*NINT(POPB/1000.0)
PRINT*,'POPULATION A',POPA,'POPULATION B',POPB
N=N+1
IF(POPA.LT.POPB) GO TO 100
PRINT*,'IN',N,'YEARS THE POPULATION OF A EXCEED B'
STOP
END

