PRINT*,'ENTER ID ,RATE AND HOUR RESPECTIVELY'
READ*,ID,RATE,HOUR
!HOURLY RATE IS WAGE
WAGE=RATE
DINCOME=RATE*HOUR
FTAX=DINCOME*(15.0/100.0)
STAX=DINCOME*(2.5/100.0)
TPAY=DINCOME-(FTAX+STAX)
WRITE(6,12),ID,HOUR,WAGE,FTAX,STAX,TPAY
12 FORMAT(1X,I9,3F8.0,2F10.2)
STOP
END



