DIMENSION JSET(5),KSET(5),INTER(10),IUNION(10)
PRINT*,'ENTER JSET '
DO 100 I=1,5
    READ*,JSET(I)
100 CONTINUE
PRINT*,'ENTER KSET'
DO 200 J=1,5
    READ*,KSET(J)
200 CONTINUE

PRINT*,'UNION SET'
DO I=1,10
    WRITE(*,'(I2)',ADVANCE='NO'), IUNION(I)
END DO
PRINT*,'INTERSECTON SET'

DO 300 K=1,10
    WRITE(*,'(I2)',ADVANCE='NO'), INTER(K)
300 CONTINUE
STOP
END
