DIMENSION B(10),BB(10)
DO 100 I=1,10
    READ*,B(I)
    BB(I)=ABS(B(I))
100 CONTINUE
BIG=0.0
L=1
DO 200 K=1,10
    IF(BB(K).GT.BIG) BIG=BB(K)
    IF(BB(K).GT.BIG) GO TO 20
    20 L=K
200 CONTINUE
PRINT*,'LARGEST NUMBER IN MEMORY LOCATION NO.:',L
PRINT*,'LARGEST NUMBER IN ARRAY IS',BIG
STOP
END
