
PRINT*,'ENTER THE AMOUNT AND RATE IN PERCENTAGE'
READ*,AMOUNT,R
RATE=R/100.0
PRINT*,'ENTER HOW MANY YEAR'
READ*,N
A=AMOUNT
REPAY=25.0
J=N*12
DO 100 I=1,J
    A=A+(A*RATE)-REPAY
WRITE(6,12),I,A
12 FORMAT('AT THE END OF MONTH ',1X,I5,':  HE OWES',2X,F12.4)
100 CONTINUE
STOP
END

