PRINT*,'ENTER A , B AND C'
READ*,A,B,C
IF((A**2+B**2.EQ.C**2).OR.(A**2+C**2.EQ.B**2).OR.(B**2+C**2.EQ.A**2)) GO TO 100
PRINT*,A,B,C, 'IS NOT A PYTHAGOREAN TRIPLET'
STOP
100 PRINT*,A,B,C,'IS A PYTHAGOREAN TRIPLET'
STOP
END
