PRINT*,'ENTER HOW MANY NUMBER DO YOU WANT TO ENTER'
READ*,N
PRINT*,'ENTER NUMBERS'
READ*,I
READ*,J
IF(I.GE.J) LAR1=I
LAR2=J
DO 100 K=3,N
    READ*,L

    IF(L.GT.LAR1) GO TO 30
    30 LAR2=LAR1
       LAR1=L

100 CONTINUE
PRINT*,'LARGEST NUMBER IS',LAR1,'2ND LARGEST  NUMBER IS',LAR2
STOP
END
