PRINT*,'ENTER HOW MANY NUMBER DO YOU WANT TO ENTER'
READ*,N
PRINT*,'ENTER NUMBERS'
50 READ*,I
IF(MOD(I,2).NE.0) GO TO 50
LAR=I
DO 100 K=1,N
    READ*,L
    IF(L.GT.LAR) GO TO 30
     GO TO 100
    30 IF(MOD(L,2).EQ.0) LAR=L

100 CONTINUE
PRINT*,'LARGEST EVEN NUMBER',LAR
STOP
END
