REAL MEAN
SUM=0.0
SUMSQ=0.0
PRINT*,'HOW MANY NUMBERS'
READ*,N
DO 100 I=1,N
    READ*,X
    SUM=SUM+X
    SUMSQ=SUMSQ+X**2
100 CONTINUE
P=FLOAT(N)
PRINT*,'SUM:',SUM,'SUM OF SQUARES:',SUMSQ
MEAN=SUM/P
VARIANCE=(SUMSQ/P)-MEAN**2
SD=SQRT(VARIANCE)
PRINT*,'MEAN:',MEAN,'VARIANCE:',VARIANCE,'STANDARD DAVIATION:',SD
STOP
END
