IP=0
IN=0
DO 100 I=1,10
    READ*,N
    IF(N.LT.0) IN=IN+1
    IF(N.GT.0) IP=IP+1
    IF (N.EQ.0) GO TO 100
    100 CONTINUE
PRINT*,'NUMBER OF POSITIVE NUMBER IS',IP,'AND NEGATIVE NUMBER IS',IN
STOP
END
